services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: nicetas
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: bookcrud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
